#pragma once

#include "Components/Animator.h"
#include "Components/Attack.h"
#include "Components/CameraTarget.h"
#include "Components/Vampire.h"
#include "Components/Dash.h"
#include "Components/Health.h"
#include "Components/Movement.h"
#include "Components/PlayerInput.h"
#include "Components/RigidBody.h"
#include "Components/Stats.h"
#include "Components/Tag.h"
#include "Components/Transform.h"
#include "Components/ActorAudioSource.h"
#include "Components/AmbienceAudioSource.h"
#include "Components/Aggresion.h"
#include "Components/Inventory.h"
#include "Components/Patrol.h"
#include "Components/Dispose.h"
#include "Components/Stamina.h"
#include "Components/BossFightArena.h"
#include "Components/Item.h"
#include "Components/Description.h"
#include "Components/Icon.h"
#include "Components/ItemOwner.h"
#include "Components/JustEquiped.h"
#include "Components/JustUnequiped.h"
#include "Components/Equiped.h"
#include "Components/HealthBoost.h"
#include "Components/CurrentScreen.h"
#include "Components/NPC.h"

#include "Components/PlayerTemporal.h"
#include "Components/BossTemporal.h"
#include "Components/Dialogue.h"
#include "Components/Stats.h"

//FSM
#include "Src/FSM/Components/PlayerStates.h"

